.

diff --git a/.github/actions/upload-artifacts-to-s3/action.yml b/.github/actions/upload-artifacts-to-s3/action.yml
--- a/.github/actions/upload-artifacts-to-s3/action.yml
+++ b/.github/actions/upload-artifacts-to-s3/action.yml
@@ -23,36 +23,41 @@ runs:
     - name: Configure AWS credentials and upload artifcats # todo - use aws role instead
       shell: bash
       run: |
-          echo ::group::install aws cli
-          python3 -m venv .aws-cli-venv && source .aws-cli-venv/bin/activate &&
-          pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
-          echo ::endgroup::
+        if command -v scl_source &> /dev/null
+        then
+            . scl_source enable devtoolset-11 || true
+        fi
+        . venv/bin/activate 
 
-          # Variables from the workflow
-          export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
-          export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
-          export AWS_REGION="us-east-1"
-          # Check if the required environment variables are set
-          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
-            echo "Missing AWS credentials or region configuration."
-            exit 1
+        echo ::group::install aws cli
+        pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
+        echo ::endgroup::
+
+        # Variables from the workflow
+        export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
+        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
+        export AWS_REGION="us-east-1"
+        # Check if the required environment variables are set
+        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
+          echo "Missing AWS credentials or region configuration."
+          exit 1
+        fi
+        # Configure AWS CLI with provided credentials and region
+        echo "Configuring AWS CLI with access keys..."
+        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
+        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
+        aws configure set region "$AWS_REGION"
+
+        echo ::group::upload artifacts
+          SHOW=1 VERBOSE=1 make upload-artifacts
+        echo ::endgroup::
+        echo ::group::upload staging release
+          STAGING=1 SHOW=1 VERBOSE=1 make upload-artifacts
+        echo ::endgroup::
+        
+        echo ::group::upload production release
+          # todo: trigger this manually instead
+          if [[ "${{ inputs.github-ref}}" != 'refs/heads/master' ]]; then
+            SHOW=1 VERBOSE=1 make upload-release
           fi
-          # Configure AWS CLI with provided credentials and region
-          echo "Configuring AWS CLI with access keys..."
-          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
-          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
-          aws configure set region "$AWS_REGION"
-
-          echo ::group::upload artifacts
-            SHOW=1 VERBOSE=1 make upload-artifacts
-          echo ::endgroup::
-          echo ::group::upload staging release
-            STAGING=1 SHOW=1 VERBOSE=1 make upload-artifacts
-          echo ::endgroup::
-          
-          echo ::group::upload production release
-            # todo: trigger this manually instead
-            if [[ "${{ inputs.github-ref}}" != 'refs/heads/master' ]]; then
-              SHOW=1 VERBOSE=1 make upload-release
-            fi
-          echo ::endgroup::
+        echo ::endgroup::
